### ISSUE TITLE
`Metadata Test` Runs without being specified 

### ISSUE THREAD

**Issue by paparaka** [GoogleContainerTools/container-structure-test#121]
The application does not like my entrypoint and the test unit fails with an error,
but for some reason `metadata test` is executed and I get an overall `PASS`.
This could potentially be mistaken by someone (that is too busy too look at the output)
to be a successful test of their code. 

```
ERRO[0000] Please provide a valid entrypoint to run for test System Test 
=== RUN: [Metadata Test]
--- PASS
===============
=== RESULTS ===
===============
Passes:      1
Failures:    0
Total tests: 1

PASS
```
Here is the config file used:
```
schemaVersion: '2.0.0' # Make sure to test the latest schema version
commandTests:

- name: 'System Test'
  setup: ['/sbin/setuser', elasticsearch', '/usr/share/elasticsearch/bin/elasticsearch']
  command: ['/system_test.bash']
  expectedOutput: ['.*Elasticsearch is up.*']
```
