### ISSUE TITLE
Feature request: Regex support in env-variable tests

### ISSUE THREAD

**Issue by andmos** [GoogleContainerTools/container-structure-test#145]
Just a quick request, 
when running a `metadataTest` like
```
metadataTest:
      env:
        - key: DOTNET_SDK_VERSION
          value: 2.1.300
```
It would be nice to have regex support in the `value:` field, like
```
metadataTest:
      env:
        - key: DOTNET_SDK_VERSION
          value: "2.1.*"
```
My case is that the baseimage I use can be pulled on a less detailed semantic level (`dotnet:2.1-sdk` vs. `dotnet:2.1.3-sdk`) so it would be nice to not have to change the tests each time a new patch release comes out when I don't actually care about it.
