### ISSUE TITLE
Display docker commands used to execute tests

### ISSUE THREAD

**Issue by hhoechtl** [GoogleContainerTools/container-structure-test#169]
I'm trying to test a ENV based switch from my entrypoint:

```sh
if [[ -n "${PHP_DEBUGGER+x}" ]]; then
    case "$PHP_DEBUGGER" in
        xdebug)
            echo "PHP-Debugger: Xdebug enabled"
            phpModuleRemove "blackfire"
            ;;

        blackfire)
            echo "PHP-Debugger: Blackfire enabled"
            phpModuleRemove "xdebug"
            docker-service-enable blackfire-agent
            ;;

        none)
            echo "PHP-Debugger: none"
            phpModuleRemove "blackfire"
            phpModuleRemove "xdebug"
            ;;
    esac
else
    echo "PHP-Debugger: not specified - default is xdebug"
    phpModuleRemove "blackfire"
fi
```

By using:

```yaml
commandTests:
  - name: "xdebug enabled by default"
    command: "php"
    args: ["-m"]
    expectedOutput:
      - "Xdebug"
    excludedOutput:
      - "blackfire"
  - name: "PHP_DEBUGGER change to blackfire"
    envVars:
    - key: "PHP_DEBUGGER"
      value: "blackfire"
    command: "php"
    args: ["-m"]
    expectedOutput:
      - "blackfire"
    excludedOutput:
      - "Xdebug"
```

But the test fails with `Error: Excluded string 'Xdebug' found in output` and `Error: Excluded string 'blackfire' found in output`, because the output of the test contains this:

```
[Zend Modules]
Xdebug
Zend OPcache
blackfire
```

If I try to verify this using a manual command like:

```
docker run --rm -ti -e PHP_DEBUGGER=blackfire webdevops/php-dev:7.0 php -m
```
The output is:
```
[Zend Modules]
Zend OPcache
blackfire
```

Respectively
```
docker run --rm -ti -e PHP_DEBUGGER=xdebug webdevops/php-dev:7.0 php -m
```
The output is:
```
[Zend Modules]
Xdebug
Zend OPcache
```

Therefore there must be a difference between what is executed by the commandTests and doing a manual run command.

**Comment by hhoechtl** [comment]
I just noticed I've overseen the chapter about entrypoints, but nevertheless it doesn't work.

Here's my adaptation:
```yaml
commandTests:
  - name: "xdebug enabled by default"
    setup: [["/entrypoint"]]
    command: "php"
    args: ["-m"]
    expectedOutput: ["Xdebug"]
    excludedOutput: ["blackfire"]
  - name: "PHP_DEBUGGER change to blackfire"
    setup: [["/entrypoint"]]
    envVars:
    - key: "PHP_DEBUGGER"
      value: "blackfire"
    command: "php"
    args: ["-m"]
    expectedOutput: ["blackfire"]
    excludedOutput: ["Xdebug"]
```

By looking at the code and debugging, I can't figure out, where the `setup` is used.
