### ISSUE TITLE
cannot reuse .env  in   expectedOutput

### ISSUE THREAD

**Issue by abdennour** [GoogleContainerTools/container-structure-test#196]
My images are built by docker compose based on ARGs which are taken values from `.env`. 

I would like to make the assertion accordingly:

```env
NODE_TAG=11.8.0
```

```yml
schemaVersion: '2.0.0'

globalEnvVars:
  - key: "NODE_TAG"
    value: "$NODE_TAG"
commandTests:
  - name: "node version"
    command: "node"
    args: ["-v"]
    expectedOutput: ["$NODE_TAG"]
```

When I ran tests, I got: 

```
--- FAIL
stdout: v11.8.0
Error: Expected string '$NODE_TAG' not found in output 'v11.8.0
```
