### ISSUE TITLE
"exec: \"type\": executable file not found in $PATH": unknown

### ISSUE THREAD

**Issue by mvilrokx** [GoogleContainerTools/container-structure-test#235]
I am trying to check the existence of certain commands in my container.  The container uses `centos:7` as the `FROM` image.  

Since centos does not have the `which` command, I am using the (bash) builtin `type` command with the `-P` flag to verify the path of the commands I need.  However, this results in:

`"exec: \"type\": executable file not found in $PATH": unknown`

I.e. it seems that the tool cannot find/use builtin commands?

I verified in the running container and `type` works fine, e.g.:

```shell
[root@2418b2fe1644 ~]# type -P grep
/usr/bin/grep
```

**Comment by mvilrokx** [comment]
ugh, never mind, I need to use `bash -c` I guess, that seems to work:

```yml
commandTests:
  - name: "verify existence of curl"
    command: "bash"
    args: ["-c", "type -P curl"]
    expectedOutput: ["/usr/bin/curl"]
```
