### ISSUE TITLE
dynamic linkage checks

### ISSUE THREAD

**Issue by errordeveloper** [GoogleContainerTools/container-structure-test#258]
It would be great to be able to check linkage.
It's currently possible with `commandTests`, but only if `ldd` is present (often not the case for minimal images) and it requires matching the output, which can be tricky to actually implement.

Example:

```YAML
elfBinaryTests:
- name: "bash is dynamically linked"
   path: "/bin/bash"
   noMissingLibs: true
   libraries:
   - "linux-vdso.so.1"
   - "libtinfo.so.6"
   -  "libdl.so.*"
   - "libc.so.6"
   - "ld-linux-*.so.*"
```
