### ISSUE TITLE
Metadata Cmd test failing but reported expected and actual values are identical

### ISSUE THREAD

**Issue by mjeco** [GoogleContainerTools/container-structure-test#278]
The Metadata Cmd test is returning failing but the actual and expected CMD values are the same.

```bash
=== RUN: Metadata Test
--- FAIL
duration: 0s
Error: Image Cmd [/bin/sh -c /usr/local/bin/python main.py] does not match expected Cmd: [/bin/sh -c /usr/local/bin/python main.py]
```

I'm  running this with `gcr.io/gcp-runtimes/container-structure-test:v1.10.0 ` and the following `config.yaml`

```yaml
schemaVersion: 2.0.0
metadataTest:
  cmd: ["/bin/sh -c /usr/local/bin/python main.py"]
```

The error message comes from [metadata.go:L135](https://github.com/GoogleContainerTools/container-structure-test/blob/v1.10.0/pkg/types/v2/metadata.go#L135) which compares `len(*mt.Cmd)` to `len(imageConfig.Cmd)`.
