### ISSUE TITLE
Env variables are not being substituted by its actual value in commandTests

### ISSUE THREAD

**Issue by AlbertoSH** [GoogleContainerTools/container-structure-test#98]
It seems like when running the tool inside Docker it's not using the defined env variables nor the existing ones. For example, for plain `alpine` images we have `$HOME` defined:

```
$ docker run -it --rm alpine /bin/sh
/ # echo $HOME
/root
/ #
```

But when trying to use it in a test it's not being substituted by its `/root` value. Neither the defined ones (both locally and global variables) seem to work. Having a test file like this:

```
schemaVersion: "2.0.0"
globalEnvVars:
  - key: "GLOBAL_VAR"
    value: "GLOBAL_VALUE"
commandTests:
  - name: "existing env variable"
    command: "echo"
    args: ["$HOME"]
    expectedOutput: ["/root"]
  - name: "local env variable"
    envVars:
      - key: "SOME_ENV"
        value: "someValue"
    command: "echo"
    args: ["$SOME_ENV"]
    expectedOutput: ["someValue"]
  - name: "global env variable"  
    command: "echo"
    args: ["$GLOBAL_VAR"]
    expectedOutput: ["GLOBAL_VALUE"]
```

and executing the tests with

```
docker run --rm \
    -v `pwd`:/tests \
    -v /var/run/docker.sock:/var/run/docker.sock \
    gcr.io/gcp-runtimes/container-structure-test:v1.0.0 \
    test \
    --image alpine \
    --config /tests/tests.yaml \
    -v
```

not a single tests pass:

```
===================================
====== Test file: tests.yaml ======
===================================
Total tests run: 3

=== RUN: [Command Test: existing env variable]
--- FAIL
stdout: $HOME

Error: Expected string '/root' not found in output

=== RUN: [Command Test: local env variable]
--- FAIL
stdout: $SOME_ENV

Error: Expected string 'someValue' not found in output

=== RUN: [Command Test: global env variable]
--- FAIL
stdout: $GLOBAL_VAR

Error: Expected string 'GLOBAL_VALUE' not found in output

FAILURES: 3
FAIL
```

**Comment by nkubala** [comment]
Hey @AlbertoSH, thanks for filing and sorry for the late reply on this one.

container-structure-test doesn't currently support environment variable substitution in the test spec itself, so you won't be able to use any env vars as part of your test args/output. However, what you're trying to do is still possible using the `metadataTest`:

```
schemaVersion: 2.0.0

globalEnvVars:
  - key: FOO
    value: test_value

metadataTest:
  env:
    - key: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - key: FOO
      value: test_value
```

You can specify all your env vars here and check to be sure they're set to the correct value. It's also worth noting that this will NOT let you check variables set by the OS at boot or login time, i.e. `$HOME`, as these are not part of the container config.

All that said, I did actually find an issue with setting the env vars outside of the `CommandTests`: opened an issue for that [here](https://github.com/GoogleCloudPlatform/container-structure-test/issues/107).

**Comment by AlbertoSH** [comment]
Yes, I know that I can test the env variables with the metadataTest but my use case was more intended to check that some software was installed and its executable was added to the PATH. So my real test is something like:

```
schemaVersion: "2.0.0"
globalEnvVars:
  - name: "some specific software version"
    envVars:
      - key: "PATH"
        value: "$PATH:$HOME/some/dir"
    command: "someExecutableAvailableInPath"
    args: ["some", "args"]
    expectedOutput: ["Version X"]
```

In the end I got a similar result with:
```
schemaVersion: "2.0.0"
globalEnvVars:
  - name: "some specific software version"
    # PATH redefinition not needed since it's set in .bashrc
    command: "bash"
    args: ["-cl", "someExecutableAvailableInPath some args"]
    expectedOutput: ["Version X"]
```

But it feels like an ugly workaround
